// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoD0cYU-jzEANBSii63LUxRul-QML7iPY',
    appId: '1:235379009895:web:54a910e0a3b0aa611567c2',
    messagingSenderId: '235379009895',
    projectId: 'chat-app-179e2',
    authDomain: 'chat-app-179e2.firebaseapp.com',
    storageBucket: 'chat-app-179e2.appspot.com',
    measurementId: 'G-S4T3WS8KNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPUrJ2o8FecTcPED-4wqVOpI-ADsRnvLc',
    appId: '1:235379009895:android:6ea5faafaaceecf81567c2',
    messagingSenderId: '235379009895',
    projectId: 'chat-app-179e2',
    storageBucket: 'chat-app-179e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC47Yisz9uXYwC0ck3_YrV3kzxWlErlf5c',
    appId: '1:235379009895:ios:e6e2fa26e208bd141567c2',
    messagingSenderId: '235379009895',
    projectId: 'chat-app-179e2',
    storageBucket: 'chat-app-179e2.appspot.com',
    androidClientId: '235379009895-a8nsv7rh4g4ek4mlsan4kt1h5bsgf4qo.apps.googleusercontent.com',
    iosClientId: '235379009895-uf630n2mm8l3q9q173r47g7uoqcfdl4t.apps.googleusercontent.com',
    iosBundleId: 'com.deytri.chatApp',
  );
}
